### ISSUE TITLE
gzip: : unexpected end of file

### ISSUE THREAD

**Issue by Halama** [keboola/storage-api-php-client#101] opened 2016-12-04 10:22 UTC
https://connection.keboola.com/admin/utils/logs?file=2016/12/03/02/2016-12-03-02-54-41-584225e13e0d4-exception

**Comment by ErikZigo** [comment] 2021-08-28 16:33
Cannot reproduce and find similar issue in our logs. Closing.

**Closed by ErikZigo** 2021-08-28 16:33 UTC
Labels: bug
